---
- name: Add repository key to the system
  apt_key:
    url: https://mariadb.org/mariadb_release_signing_key.asc
    state: present
  become: true
  tags: mariadb

- name: Check if mariadb repository exists
  stat:
    path: /etc/apt/sources.list.d/mariadb.list
  register: mariadb_added
  become: true
  tags:
    - mariadb

# https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
- name: Get install script
  copy:
    src: mariadb_repo_setup
    dest: /tmp/mariadb_repo_setup
    mode: 0775
    owner: root
    group: root
  become: true
  when: mariadb_added.stat.exists == false
  tags:
    - mariadb

- name: Install repository
  shell: /tmp/mariadb_repo_setup --mariadb-server-version=mariadb-{{ MARIADB_VERSION }}
  become: true
  when: mariadb_added.stat.exists == false
  tags:
    - mariadb

- name: Install Server
  apt:
    pkg: mariadb-server
    state: present
    update_cache: true
  become: true
  tags: mariadb

- name: Install python-mysqldb
  apt:
    pkg: python3-mysqldb
    state: present
    update_cache: true
  become: true
  tags: mariadb

- name: Set MariaDB root password for the first time (root@localhost)
  mysql_user:
    name: root
    password: "{{ MYSQL_ROOT_PASSWORD }}"
    host: localhost
    login_user: root
    state: present
  when: MYSQL_ROOT_PASSWORD is defined
  become: true
  tags: mariadb

- name: Set MariaDB root password for 127.0.0.1, ::1
  mysql_user:
    name: root
    password: "{{ MYSQL_ROOT_PASSWORD }}"
    host: "{{ item }}"
    login_user: root
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    state: present
  with_items:
    - ::1
    - 127.0.0.1
  when: MYSQL_ROOT_PASSWORD is defined
  become: true
  tags: mariadb

- name: Copy .my.cnf file with root password credentials - root
  template:
    src: root.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  when: MYSQL_ROOT_PASSWORD is defined
  become: true
  tags: mariadb

- name: Copy .my.cnf file with root password credentials - {{ NORMAL_USER_NAME }}
  template:
    src: root.cnf.j2
    dest: "/home/{{ NORMAL_USER_NAME }}/.my.cnf"
    owner: "{{ NORMAL_USER_NAME }}"
    group: "{{ NORMAL_USER_NAME }}"
    mode: 0600
  when: MYSQL_ROOT_PASSWORD is defined
  become: true
  tags: mariadb

- name: Change default listen address (if docker setup)
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address.*=.*127\.0\.0\.1$'
    line: 'bind-address            = 0.0.0.0'
  when: (DOCKER is defined) and (MYSQL_ROOT_PASSWORD is defined)
  become: true
  tags: mariadb

- name: Set transaction istolation to "READ-COMMITTED"
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    insertafter: '^tmpdir'
    line: 'transaction_isolation = "READ-COMMITTED"'
  become: true
  tags: mariadb

# Yes, that file is depecreated by mariadb, but still used in service start.
- name: Set default passsword in /etc/mysql/debian.cnf
  template:
    src: debian.cnf.j2
    dest: "/etc/mysql/debian.cnf"
    owner: root
    mode: 0600
  when: MYSQL_ROOT_PASSWORD is defined
  become: true
  tags:
    - mariadb

- name: Cron SQL check optimization
  cron:
    name: SQL incremental backup
    weekday: "*"
    minute: "0"
    hour: "1"
    user: root
    job: "/usr/bin/mysqlcheck -o --all-databases > /dev/null 2>&1"
    cron_file: mysqlcheck
  become: true
