---
- name: Install required system packages
  apt:
    pkg:
      - 'apt-transport-https'
      - 'ca-certificates'
      - 'curl'
      - 'software-properties-common'
    state: present
    update_cache: true
  become: true
  tags:
    - docker

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true
  tags:
    - docker

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
  become: true
  tags:
    - docker

- name: Update apt and install docker-ce
  apt:
    pkg: docker-ce
    state: present
    update_cache: true
  become: true
  tags:
    - docker

- name: Stop docker-ce
  service:
    name: docker
    state: stopped
  become: true
  tags:
    - docker
    - docker-config
    
- name: Copy default docker daemon configuration
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  become: true
  tags:
    - docker
    - docker-config

- name: Move docker data dir
  shell: mv /var/lib/docker /data/docker
  become: true
  tags:
    - docker
    - docker-config

- name: Start docker-ce
  service:
    name: docker
    state: started
  become: true
  tags:
    - docker
    - docker-config

- name: Added root user to docker group
  user: 
    name: "{{ ROOT_USER_NAME }}"
    groups: docker 
    append: yes
  become: true
  tags:
    - docker

- name: Added normal user to docker group
  user: 
    name: "{{ NORMAL_USER_NAME }}"
    groups: docker
    append: yes
  become: true
  tags:
    - docker

- name: Update apt and install docker compose
  apt:
    pkg: docker-compose-plugin
    state: present
    update_cache: true
  become: true
  tags:
    - docker
