---
- name: Install ubuntu drivers
  apt:
    pkg:
      - 'ubuntu-drivers-common'
    state: present
  become: true
  tags:
    - gpu

- name: Download CUDA keyring
  get_url: 
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
    dest: /tmp/cuda-keyring_all.deb
    mode: 0755
  become: true
  tags:
    - gpu

- name: Install CUDA keyring
  shell: apt install -y /tmp/cuda-keyring_all.deb
  become: true
  tags:
    - gpu

- name: Apt update
  shell: apt update
  become: true
  tags:
    - gpu

# Very important that secure boot is not eabled in azure.
- name: Install drivers
  shell: ubuntu-drivers install
  become: true
  tags:
    - gpu

# https://learn.microsoft.com/en-us/azure/virtual-machines/linux/n-series-driver-setup
- name: Install CUDA toolkit
  apt:
    pkg:
      - 'cuda-toolkit-12-3'
      - 'nvidia-container-toolkit'
    state: present
    update_cache: true
  become: true
  tags:
    - gpu

# - name: Install CUDA SDK
#   apt:
#     pkg:
#       - 'nvidia-gds'
#     state: present
#     update_cache: true
#   become: true
#   tags:
#     - gpu